DROP TABLE IF EXISTS users;

CREATE TABLE users (
    photo text,
    name text NOT NULL,
    address text,
    phone text,
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);  
INSERT INTO users (photo, name, address, phone) VALUES ('https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/415.jpg','Beulah Mills', '30029 Kristina Isle', '765.765.6517');
INSERT INTO users (photo, name, address, phone) VALUES ('https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/985.jpg','Traci Bartoletti', 'Mackenzie Mills', '370-446-7591');