DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS companies;

CREATE TABLE companies (
    id SERIAL PRIMARY KEY,
    name text NOT NULL,
    location text
);  
INSERT INTO companies (name, location) VALUES ('Microsoft', 'Washington');
INSERT INTO companies (name, location) VALUES ('Apple', 'California');
INSERT INTO companies (name, location) VALUES ('Google', 'California');

CREATE TABLE users (
    photo text,
    name text NOT NULL,
    address text,
    phone text,
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
   
    
);  
INSERT INTO users (photo, name, address, phone) VALUES ('https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/415.jpg','Beulah Mills', '30029 Kristina Isle', '765.765.6517');
INSERT INTO users (photo, name, address, phone) VALUES ('https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/985.jpg','Traci Bartoletti', 'Mackenzie Mills', '370-446-7591');
INSERT INTO users (name, address, phone ) VALUES ('Kelly', '789 Go away ave', 32342342);
INSERT INTO users (name, address, phone ) VALUES ('Carlson', '1969 Moon Man', 32342342);
INSERT INTO users (name, address, phone ) VALUES ('Bruno', '789 Go away ave', 32342342);
INSERT INTO users (name, address, phone ) VALUES ('Micky', '556 pew pew st', 32342342);




-- CREATE TABLE people (
--     id SERIAL PRIMARY KEY,
--     first_name text NOT NULL,
--     location text NOT NULL,
--     company_id integer,
--     CONSTRAINT fk_companies FOREIGN KEY(company_id) REFERENCES companies(id)
-- )
-- INSERT INTO companies (name, location) VALUES ('Microsoft', 'Washington');
-- INSERT INTO companies (name, location) VALUES ('Apple', 'California');
-- INSERT INTO companies (name, location) VALUES ('Google', 'California');
-- INSERT INTO people (first_name, location, company_id, ) VALUES ('Micheal', 'Washington', 1);
-- INSERT INTO people (first_name, location, company_id, ) VALUES ('Micky', 'California', 2);
-- INSERT INTO people (first_name, location, company_id, ) VALUES ('Mitch', 'California', 3);